/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from "@tanstack/react-router"

// Import Routes

import { Route as rootRoute } from "./routes/__root"

// Create Virtual Routes

const appRouteLazyImport = createFileRoute("/(app)")()

// Create/Update Routes

const appRouteLazyRoute = appRouteLazyImport
  .update({
    path: "/",
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import("./routes/(app)/route.lazy").then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/(app)": {
      preLoaderRoute: typeof appRouteLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([appRouteLazyRoute])

/* prettier-ignore-end */
