name: CI

on:
  workflow_dispatch:
  push:

jobs:
  format:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node and Bun
        uses: jdx/mise-action@v2
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Format
        run: bun run format:check

  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node and Bun
        uses: jdx/mise-action@v2
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Lint
        run: bun run lint

  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node and Bun
        uses: jdx/mise-action@v2
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Build
        run: bun run build

  vitest:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node and Bun
        uses: jdx/mise-action@v2
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Run Vitest tests
        run: bun run vitest:ci

  storybook:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node and Bun
        uses: jdx/mise-action@v2
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Install Playwright browsers
        run: bunx playwright install --with-deps
      - name: Run Storybook tests
        run: bun run storybook:test:ci
