name: Publish to Cloudflare Pages

on:
  workflow_dispatch:
  push:

jobs:
  publish:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout respository
        uses: actions/checkout@v4

      - name: Setup Node and Bun
        uses: jdx/mise-action@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build website
        run: bun run build

      - name: Build storybook
        run: bun run storybook:build && mv storybook-static dist/storybook

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: r4ai-yumemi-passport-frontend-2024
          directory: ./dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
